import { Theme, darken } from "@mui/material/styles";
import { DashboardStyles } from "./types";

export const getDashboardStyles = (theme: Theme): DashboardStyles => ({
  rootContainer: {
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    py: { xs: 4, sm: 6, md: 8 },
    px: { xs: 2, sm: 3, md: 4 },
    background: theme.palette.gradients.darkPrimary,
    overflowY: "auto",
    overflowX: "hidden",
    position: "absolute",
    top: 0,
    left: 0,
    color: theme.palette.text.primary,
  },
  dashboardContent: {
    width: "100%",
    maxWidth: 1280,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: theme.spacing(4),
    p: { xs: 2, sm: 3, md: 4 },

    borderRadius: theme.shape.borderRadius,
    overflow: "hidden",
  },
  headerBox: {
    width: "100%",
    display: "flex",
    flexDirection: { xs: "column", sm: "row" },
    justifyContent: "space-between",
    alignItems: "center",
    gap: theme.spacing(4),
    marginBottom: theme.spacing(2),
  },
  title: {
    fontWeight: 500,
    color: theme.palette.primary.light,
    textShadow: `0 0 10px ${theme.palette.glow.main}60`,
    fontSize: "2rem",
    textAlign: { xs: "center", sm: "left" },
    width: "100%",
  },
  logoutButton: {
    py: 1,
    px: 3,
    borderRadius: theme.shape.borderRadius,
    bgcolor: theme.palette.error.main,
    color: theme.palette.error.contrastText,
    transition:
      "background-color 0.3s ease-in-out, box-shadow 0.3s ease-in-out, transform 0.2s ease-in-out",
    "&:hover": {
      bgcolor: theme.palette.error.dark,
      boxShadow: `0 6px 12px ${darken(theme.palette.error.main, 0.5)}`,
      transform: "translateY(-2px)",
    },
    "&:active": {
      transform: "translateY(0)",
      boxShadow: `0 2px 8px ${darken(theme.palette.error.main, 0.3)}`,
    },
  },
  searchSection: {
    width: "100%",
    display: "flex",
    justifyContent: "center",
    marginBottom: theme.spacing(3),
  },
  resultsSection: {
    width: "100%",
    minHeight: "200px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
  },
  loadingIndicator: {
    mt: 4,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 2,
    color: theme.palette.text.primary,
  },
  errorAlert: {
    mb: 2,
    borderRadius: theme.shape.borderRadius,
    width: "100%",
    boxShadow: theme.shadows[2],
  },
  noResults: {
    color: theme.palette.text.secondary,
    mt: 4,
    textAlign: "center",
    lineHeight: 1.5,
  },
  movieGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(4, 1fr)",
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: theme.spacing(5),
    width: "100%",
    paddingY: theme.spacing(1),
    marginBottom: theme.spacing(4),
  },
  movieCardWrapper: {
    flexShrink: 0,
    display: "flex",
    justifyContent: "center",
  },
  paginationContainer: {
    mt: theme.spacing(4),
    mb: theme.spacing(2),
    display: "flex",
    justifyContent: "center",
  },
});
